broadway:
    read_model: broadway.read_model.mongodb.repository_factory

services:
    broadway.read_model.mongodb_client:
        class: MongoDB\Client
        arguments: ['%env(BROADWAY_READ_MODEL_MONGODB_URI)%']

    broadway.read_model.mongodb_collection:
        class: MongoDB\Collection
        factory: ['@broadway.read_model.mongodb_client', selectCollection]
        arguments: ['%env(BROADWAY_READ_MODEL_MONGODB_DATABASE)%', 'read_models']

    broadway.read_model.mongodb.repository_factory:
        class: Broadway\ReadModel\MongoDB\MongoDBRepositoryFactory
        arguments:
            - "@broadway.read_model.mongodb_collection"
            - "@broadway.serializer.readmodel"
