# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\ApiController:
        arguments:
            - '@broadway.command_handling.command_bus'
            - '@broadway.uuid.generator'
            - '@app.travel.read_model.repository'
            - '@app.section.read_model.repository'
            - '@app.station.read_model.repository'
        tags: ['controller.service_arguments']


    app.station.read_model.repository:
        class: Broadway\ReadModel\ReadModel
        factory: ['@broadway.read_model.mongodb.repository_factory', create]
        arguments: ['', 'App\ReadModel\Station']

    app.section.read_model.repository:
         class: Broadway\ReadModel\ReadModel
         factory: ['@broadway.read_model.mongodb.repository_factory', create]
         arguments: ['', 'App\ReadModel\Section']

    app.travel.read_model.repository:
         class: Broadway\ReadModel\ReadModel
         factory: ['@broadway.read_model.mongodb.repository_factory', create]
         arguments: ['', 'App\ReadModel\Travel']

    App\Console\LoadSectionsCommand:
         arguments: ['@broadway.command_handling.command_bus']

    App\Console\LoadStationsCommand:
        arguments: ['@broadway.command_handling.command_bus']

    app.section.repository:
         class: App\AppRepository
         arguments:
             - '@broadway.event_store'
             - '@broadway.event_handling.event_bus'
             - 'App\Section\Section'
             - ['@broadway.metadata_enriching_event_stream_decorator']

    App\Travel\Travel:
        properties:
            stationRepository: '@app.station.read_model.repository'

    app.travel.repository:
         class: App\AppNewRepository
         arguments:
             - '@broadway.event_store'
             - '@broadway.event_handling.event_bus'
             - 'App\Travel\Travel'
             - ['@broadway.metadata_enriching_event_stream_decorator']
             - '@app.station.read_model.repository'
             - '@app.section.read_model.repository'

    app.station.repository:
        class: App\AppRepository
        arguments:
            - '@broadway.event_store'
            - '@broadway.event_handling.event_bus'
            - 'App\Station\Station'
            - ['@broadway.metadata_enriching_event_stream_decorator']

    App\Station\StationCommandHandler:
        arguments: ['@app.station.repository']
        tags: ['broadway.command_handler']

    App\Section\SectionCommandHandler:
         arguments: ['@app.section.repository']
         tags: ['broadway.command_handler']

    App\Travel\TravelCommandHandler:
         arguments: ['@app.travel.repository']
         tags: ['broadway.command_handler']

    App\ReadModel\StationProjector:
        arguments: ['@app.station.read_model.repository']
        tags: ['broadway.domain.event_listener']

    App\ReadModel\SectionProjector:
         arguments: ['@app.section.read_model.repository']
         tags: ['broadway.domain.event_listener']

    App\ReadModel\TravelProjector:
         arguments: ['@app.travel.read_model.repository']
         tags: ['broadway.domain.event_listener']
